### ISSUE TITLE
Does not work without `/lib64/ld-linux-x86-64.so.2`

### ISSUE THREAD

**Issue by nagisa** [danburkert/prost#182] opened 2019-05-09 22:47 UTC
On certain linux systems where `/lib64/ld-linux-x86-64.so.2` does not exist, this library will attempt fail to run the vendored protoc with a fairly obscure error message:

```
thread 'main' panicked at 'Failed to compile gRPC files: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/libcore/result.rs:999:5
```

Some details:

```
$ /home/nagisa/.cargo/registry/src/github.com-1ecc6299db9ec823/prost-build-0.5.0/third-party/protobuf/protoc-linux-x86_64 -h
Failed to execute process '/home/nagisa/.cargo/registry/src/github.com-1ecc6299db9ec823/prost-build-0.5.0/third-party/protobuf/protoc-linux-x86_64'. Reason:
The file '/home/nagisa/.cargo/registry/src/github.com-1ecc6299db9ec823/prost-build-0.5.0/third-party/protobuf/protoc-linux-x86_64' does not exist or could not be executed.
$ file /home/nagisa/.cargo/registry/src/github.com-1ecc6299db9ec823/prost-build-0.5.0/third-party/protobuf/protoc-linux-x86_64 
/home/nagisa/.cargo/registry/src/github.com-1ecc6299db9ec823/prost-build-0.5.0/third-party/protobuf/protoc-linux-x86_64: ELF 64-bit LSB executable, x86-64, version 1 (GNU/Linux), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.18, BuildID[sha1]=fba3a114edbedcdd158c16be98c821067c895c93, stripped
$ ls /lib64/ld-linux-x86-64.so.2
ls: cannot access '/lib64/ld-linux-x86-64.so.2': No such file or directory
```

This will occur even if `protoc` is in `PATH`:

```
$ protoc --version
libprotoc 2.6.1
```

**Comment by danburkert** [comment] 2019-05-11 20:21
Interesting.  The `protoc` executables that `prost` ships are the umodified release binaries from the upstream project, so the dynamic libraries they rely on aren't really under our control.  As a workaround, set the `PROTOC` environment variable to point to your preferred `protoc`.  `prost-build` will only use a `protoc` on the path as a last resort, since it makes builds less portable.

**Comment by danburkert** [comment] 2019-05-11 20:22
You'll probably also want to set `PROTOC_INCLUDE`: https://github.com/danburkert/prost/blob/master/prost-build/build.rs#L1-L15.

**Comment by nagisa** [comment] 2019-05-11 20:28
I think this would be solved entirely by improving the error message, mentioning the reasons, workarounds etc.

**Comment by danburkert** [comment] 2019-05-11 20:50
It's not clear to me where the error message is even coming from; it mentions `gRPC` but nothing about `prost`.  I don't have a machine to reproduce on, so it's unlikely that I'll be able to investigate.

**Comment by nagisa** [comment] 2019-05-11 20:59
Ah, I’m sorry. The error verbatim comes from a our own build script, the part which comes from prostc is `Os { code: 2, kind: NotFound, message: "No such file or directory" }` after calling [`compile_protos`](https://docs.rs/prost-build/0.5.0/prost_build/struct.Config.html#method.compile_protos)

**Comment by danburkert** [comment] 2019-05-11 21:13
Have you been able to get this to work after setting `PROTOC`?   I have a feeling this protobuf dynamic linker thing, while a real issue, isn't actually what you're hitting.  `Os { code: 2, kind: NotFound, message: "No such file or directory" }` typically occurs when opening a file; before calling `protoc`, `compile_protos` will attempt to create a temp directory using the `tempfile` crate.  My guess is that this machine doesn't have a `/tmp` directory, and you haven't set the `TMPDIR` environment variable.

**Comment by danburkert** [comment] 2019-05-11 21:14
(I asked about `PROTOC` because if that does fix the issue, then the /tmp thing isn't failing)

**Comment by nagisa** [comment] 2019-05-11 21:21
I have set `PROTOC` to a natively installed protoc and things worked seemingly fine after that.

The NotFound comes from `execve` after the kernel(?) is not able to find the dynamic loader that is specified in the ELF file. I have verified this by looking at a syscall trace.

**Comment by danburkert** [comment] 2019-05-11 21:57
Huh, that's interesting, definitely not what I would have guessed.

**Comment by danburkert** [comment] 2019-05-25 21:48
I'm going to close this out since I don't think there's anything actionable to do in `prost`, but feel free to re-open if I'm wrong.

**Closed by danburkert** 2019-05-25 21:48 UTC
