### ISSUE TITLE
Probst compile_protobuf crashes our CI

### ISSUE THREAD

**Issue by SirVer** [danburkert/prost#67] opened 2018-01-05 14:14 UTC
This is a long shot, since we are unable to stabily reproduce the issue. Travis apparently changed something lately, and after this our `build.rs` started segfaulting. Our [build script](https://github.com/googlecartographer/point_cloud_viewer/blob/master/build.rs) only contains 

~~~rust
extern crate prost_build;
fn main() {
    prost_build::compile_protos(&["src/proto.proto"], &["src/"]).unwrap();
}
~~~

This is [our project](https://github.com/googlecartographer/point_cloud_viewer). And this is a [sample failure](https://travis-ci.org/googlecartographer/point_cloud_viewer/jobs/325129818) on travis.

Do you have any ideas where those crashes could come from? Does `prost_build` contain unsafe code?

**Comment by SirVer** [comment] 2018-01-05 14:14
@thomasschiwietz /cc

**Comment by SirVer** [comment] 2018-01-05 14:21
The main difference between two consecutive runs seems to be:

This worked:
~~~
rustc 1.23.0-beta.2 (c9107ee93 2017-12-08)
$ rustup --version
rustup 1.8.0 (cb2d14862 2017-12-17)
$ cargo --version
cargo 0.24.0-beta (6a1aee066 2017-11-18)
~~~

This failed:
~~~
rustc 1.24.0-beta.1 (5b496b726 2018-01-02)
$ rustup --version
rustup 1.8.0 (cb2d14862 2017-12-17)
$ cargo --version
cargo 0.25.0-beta (a88fbace4 2017-12-29)
~~~

**Comment by danburkert** [comment] 2018-01-06 18:44
Yep, this appears to be a bona-fide `rustc` bug.  They don't call it nightly for nothin'.  See https://github.com/rust-lang/rust/issues/47175.  Going to close as a dupe of #66.

**Closed by danburkert** 2018-01-06 18:44 UTC

**Comment by SirVer** [comment] 2018-01-08 08:28
Thanks! Indeed the bug is not nightly only, but also slipped into beta. Which is the real problem here, of course.
